// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqkggirijqdepvbpurvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxa2dnaXJpanFkZXB2YnB1cnZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDc3NDIsImV4cCI6MjA3MzQyMzc0Mn0.CuSut0KooEV98wpywyskpGC1EbKtn6Qa970lWrWSt2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});